<?php

namespace Plugin\BpmLinkPayment\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\BpmLinkPayment\Entity\Config;
// use Symfony\Bridge\Doctrine\RegistryInterface;
use Doctrine\Persistence\ManagerRegistry;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends AbstractRepository
{
    /**
     * ConfigRepository constructor.
     *
     *  RegistryInterface $registry # <-この行の@param削除
     *  @param ManagerRegistry $registry　# <-この行へ変更
     */
    // public function __construct(RegistryInterface $registry)
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Config::class);
    }

    /**
     * @param int $id
     *
     * @return null|Config
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
